### ISSUE TITLE
E684: list index out of range

### ISSUE THREAD

**Issue by ghost** [dNitro/vim-pug-complete#2]
I switch on automatic omni completion through `mu-complete` vim plugin. When I write something like `li#bh` in empty pug buffer I get
```
Error detected while processing function pugcomplete#CompletePug[556]..pugcomplete#Collect
IdorClass:
line  138:
E684: list index out of range: 1
```
I have not dived into `CollectIdorClass` function code, just added stub like this in line `1002` before `call remove(filelines, headstart-1, headend-1)`:
```
	if headend > len(filelines)
		let headend = len(filelines)
	endif
```

**Comment by dNitro** [comment]
fixed. https://github.com/dNitro/vim-pug-complete/commit/9972621dea5114a7c7e8eeebf2434ac9c9e32965
